// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	_ "dubbo.apache.org/dubbo-go/v3/imports"
)

import (
	"github.com/yrcs/nicehouse/api/acl/v1"
	"github.com/yrcs/nicehouse/app/bffadmin/internal/biz"
	"github.com/yrcs/nicehouse/app/bffadmin/internal/data"
	"github.com/yrcs/nicehouse/app/bffadmin/internal/service"
)

// Injectors from wire.go:
// wireApp init dubbogo application.
func wireApp(ac *v1.ACLClientImpl) *service.BFFAdmin {
	dataData := data.NewData(ac)
	aclRepo := data.NewACLRepo(dataData)
	aclUsecase := biz.NewACLUsecase(aclRepo)
	bffAdmin := service.NewBFFAdmin(aclUsecase)
	return bffAdmin
}
